version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app
permissions:
  - object: /home/ec2-user/app/scripts/install.sh
    mode: 644
    owner: ec2-user
    type:
      - file
permissions:
  - object: /home/ec2-user/app/scripts/start.sh
    mode: 644
    owner: ec2-user
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 180
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 180
